import os
import sqlite3

db_file = "dbase.db"
is_new_db = not os.path.exists(db_file)

con = sqlite3.connect(db_file)
cur = con.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS data (
        name TEXT PRIMARY KEY,
        about TEXT
    )
""")

if is_new_db:
    entries = [
('aryama', 'Oh yeah ! She is my creator,her skills are impressive to hear about and her efforts at a very young age are incredible ! She is currently Twelveth Maths Student from Sarasvati Balika Vidyalaya ... ' ),
('god', 'God is supreme divine being of force responsible for the creation and maintainance of Universe as well as a source of moral guidance and spiritual meaning ! However beliefs about god can varry among cultures ... ' ),
('narendra modi','He is serving as The Prime minister of India from May 2014 to my knowledge cutoff date in September 2021. He has been very influencial all through his political career...'),
('prime minister of india','He is serving as The Prime minister of India from May 2014 to my knowledge cutoff date in September 2021. He has been very influencial all through his political career...'),
('yogi adityanath','Yogi Adityanath, whose full name is Ajay Mohan Bisht but is commonly known as Yogi Adityanath, is an Indian politician. he is serving as the Chief Minister of the Indian state of Uttar Pradesh. He is a member of the Bharatiya Janata Party (BJP) and is associated with the Rashtriya Swayamsevak Sangh (RSS). Yogi Adityanath is known for his strong support of Hindu nationalism and has been a prominent figure in Indian politics, particularly in the state of Uttar Pradesh. '),
('cheif minister of uttar pradesh','Yogi Adityanath, whose full name is Ajay Mohan Bisht but is commonly known as Yogi Adityanath, is an Indian politician. he is serving as the Chief Minister of the Indian state of Uttar Pradesh. He is a member of the Bharatiya Janata Party (BJP) and is associated with the Rashtriya Swayamsevak Sangh (RSS). Yogi Adityanath is known for his strong support of Hindu nationalism and has been a prominent figure in Indian politics, particularly in the state of Uttar Pradesh. '),
('rahul gandhi','Rahul Gandhi is an Indian politician and a prominent member of the Indian National Congress, one of India major political parties. He has been a key figure in Indian politics and a member of the Nehru-Gandhi family, a prominent political dynasty in India. He is the son of former Prime Minister Rajiv Gandhi and former Congress President Sonia Gandhi.'),
('jawaharlal nehru','Jawaharlal Nehru was an Indian statesman and a key figure in the Indian independence movement against British colonial rule. He was born on November 14, 1889, and died on May 27, 1964. Nehru played a pivotal role in shaping the destiny of post-independence India and became the countrys first Prime Minister when India gained independence from British rule on August 15, 1947. Nehru was a close associate of Mahatma Gandhi and a leader of the Indian National Congress, which was the primary political party leading the struggle for independence. He is often referred to as Pandit Nehru. His birthday is celebrated as Childrens day all over the world '),
('first prime minister of india','Jawaharlal Nehru was an Indian statesman and a key figure in the Indian independence movement against British colonial rule. He was born on November 14, 1889, and died on May 27, 1964. Nehru played a pivotal role in shaping the destiny of post-independence India and became the countrys first Prime Minister when India gained independence from British rule on August 15, 1947. Nehru was a close associate of Mahatma Gandhi and a leader of the Indian National Congress, which was the primary political party leading the struggle for independence. He is often referred to as Pandit Nehru. His birthday is celebrated as Childrens day all over the world '),
('indra gandhi','Indira Gandhi was an Indian politician who served as the first female Prime Minister of India. She was born on November 19, 1917, and assassinated on October 31, 1984. Indira Gandhi was a prominent figure in Indian politics and was a member of the Indian National Congress party. She was the daughter of Jawaharlal Nehru, the first Prime Minister of India, and her leadership extended the Nehru-Gandhi political dynasty.'),
('rajendra prasad','Dr. Rajendra Prasad was an Indian statesman and a prominent figure in the Indian independence movement. He was born on December 3, 1884, and passed away on February 28, 1963. Dr. Rajendra Prasad is primarily known for being the first President of India. He played a crucial role in the struggle for Indias independence from British colonial rule and was an active member of the Indian National Congress. Dr. Prasad was a close associate of Mahatma Gandhi and participated in various movements and campaigns, including the Non-Cooperation Movement and the Civil Disobedience Movement.'),
('mahatma gandhi','Mahatma Gandhi, whose full name was Mohandas Karamchand Gandhi, was a prominent leader in the Indian independence movement against British colonial rule. He was born on October 2, 1869, in Porbandar, India, and was assassinated on January 30, 1948. Gandhi is widely regarded as one of the most important figures in 20th-century history due to his philosophy of nonviolent resistance, civil disobedience, and his role in achieving Indias independence.Gandhi is often referred to as Mahatma, which means Great Soul in Sanskrit, to honor his moral and spiritual leadership.'),
('father of the nation','Mahatma Gandhi, whose full name was Mohandas Karamchand Gandhi, was a prominent leader in the Indian independence movement against British colonial rule. He was born on October 2, 1869, in Porbandar, India, and was assassinated on January 30, 1948. Gandhi is widely regarded as one of the most important figures in 20th-century history due to his philosophy of nonviolent resistance, civil disobedience, and his role in achieving Indias independence.Gandhi is often referred to as Mahatma, which means Great Soul in Sanskrit, to honor his moral and spiritual leadership.'),
('atal bihari vajpayee','Atal Bihari Vajpayee was an Indian politician and poet who served three terms as the 10th Prime Minister of India, first for a term of 13 days in 1996, then for a period of 13 months from 1998 to 1999, followed by a full term from 1999 to 2004. Vajpayee was one of the co-founders and a senior leader of the BJP'),
('bhagat singh','Bhagat Singh was a prominent Indian revolutionary and freedom fighter who played a significant role in the struggle for Indias independence from British colonial rule. He was born on September 28, 1907, in Punjab, which is now part of Pakistan, and he was executed by the British authorities on March 23, 1931.'),
('rani lakshmi bai','Rani Lakshmi Bai, also known as Rani of Jhansi, was a prominent Indian queen and a leading figure in the Indian Rebellion of 1857, often referred to as the First War of Indian Independence. She was born in 1828 and passed away on June 18, 1858. Rani Lakshmi Bai is remembered for her courage, valor, and determination in resisting British colonial rule during a time when many Indian rulers and leaders were struggling against British domination.'),
('maharana pratap','Maharana Pratap, whose full name was Maharana Pratap Singh, was a prominent ruler of the Mewar region in northwestern India during the 16th century. He was born on May 9, 1540, and died on January 29, 1597. Maharana Pratap is best known for his heroic and valiant resistance against the Mughal Empire, particularly Emperor Akbar, during a period when various Rajput states were under Mughal rule. Maharana Pratap is a legendary figure in Indian history and is celebrated for his unwavering determination to defend the honor and independence of his kingdom of Mewar. He is particularly famous for the Battle of Haldighati, fought in 1576, where he and his forces fought against Akbars Mughal army. Despite facing overwhelming odds, Maharana Prataps resilience and military leadership made him a symbol of Rajput valor and resistance against foreign invaders. His life and legacy continue to be a source of inspiration and pride for many Indians, especially in the state of Rajasthan, where he is revered as a heroic figure. Maharana Prataps contributions to Indian history are remembered with great respect, and he is an enduring symbol of courage and sacrifice.'),
('draupadi murmu','Draupadi Murmu is currently serving as president of India an Indian politician who has been associated with the Bharatiya Janata Party and is known for her political work in the state of Jharkhand. She has been a member of the Jharkhand Legislative Assembly and has served in various political capacities.'),
('sachin tendulkar','Sachin Tendulkar is one of the most iconic and revered cricket players in the history of the sport. He was born on April 24, 1973, in Mumbai, India, and is often referred to as the Little Master and the God of Cricket. Tendulkars cricketing career is legendary, and he is widely regarded as one of the greatest batsmen in the history of the game.'),
('shahrukh khan','Shah Rukh Khan, often referred to as SRK, is one of the most prominent and influential actors in the Indian film industry, particularly in Bollywood. He was born on November 2, 1965, in New Delhi, India. Shah Rukh Khan is often recognized as the King of Bollywood due to his immense popularity and success in the Indian film world.'),
('ratan tata','Ratan Tata is a prominent Indian industrialist and business tycoon known for his leadership of the Tata Group, one of Indias largest and oldest conglomerates. He was born on December 28, 1937, in Mumbai, India. Ratan Tata is widely regarded as one of the most influential and respected figures in the Indian business world.'),
('lata mangeshkar','Lata Mangeshkar, often referred to as the Nightingale of India, was a legendary Indian playback singer. She was born on September 28, 1929, in Indore, India, and passed away on February 6, 2021. Lata Mangeshkar is widely regarded as one of the most iconic and influential voices in Indian music history'),
('sundar pichai','Sundar Pichai is an Indian-American business executive who serves as the Chief Executive Officer CEO of Alphabet Inc., the parent company of Google. He was born on July 12, 1972, in Chennai, India. Sundar Pichai is renowned for his role in the development and management of various Google products and services.'),
('founder of google','Sundar Pichai is an Indian-American business executive who serves as the Chief Executive Officer CEO of Alphabet Inc., the parent company of Google. He was born on July 12, 1972, in Chennai, India. Sundar Pichai is renowned for his role in the development and management of various Google products and services.'),
('mark zuckerberg','Mark Zuckerberg is an American technology entrepreneur and the co-founder and CEO of Meta Platforms, Inc. formerly known as Facebook, Inc. He was born on May 14, 1984, in White Plains, New York, USA. Mark Zuckerberg is one of the most prominent figures in the technology and social media industry.'),
('founder of facebook','Mark Zuckerberg is an American technology entrepreneur and the co-founder and CEO of Meta Platforms, Inc. formerly known as Facebook, Inc. He was born on May 14, 1984, in White Plains, New York, USA. Mark Zuckerberg is one of the most prominent figures in the technology and social media industry.'),
('elon musk','Elon Musk is a highly influential and prominent figure in the fields of technology, space exploration, and electric vehicles. He was born on June 28, 1971, in Pretoria, South Africa. Musk is known for his leadership in multiple groundbreaking companies and his visionary approach to innovation.'),
('kiran bedi','Kiran Bedi is an Indian police officer, social activist, and former tennis player. She was born on June 9, 1949, in Amritsar, India. Kiran Bedi is known for her pioneering work in the Indian Police Service IPS and her commitment to social causes.'),
('apj abdul kalam','Dr. Avul Pakir Jainulabdeen Abdul Kalam, commonly known as A.P.J. Abdul Kalam, was an Indian scientist, aerospace engineer, and politician. He was born on October 15, 1931, in Rameswaram, Tamil Nadu, India, and passed away on July 27, 2015. A.P.J. Abdul Kalam is celebrated as one of Indias most beloved and respected figures.'),
('virat kholi','Virat Kohli is an Indian international cricketer and one of the most prominent and accomplished cricket players in the world. He was born on November 5, 1988, in Delhi, India. Kohli is known for his exceptional skills as a batsman and his leadership as the captain of the Indian cricket team.'),
('chetan bhagat','Chetan Bhagat is an Indian author, columnist, and public speaker known for his bestselling novels, which often explore contemporary issues and themes relevant to young readers. He was born on April 22, 1974, in New Delhi, India. Chetan Bhagats works have gained widespread popularity in India and among the Indian diaspora.'),
('ms dhoni','M.S. Dhoni, whose full name is Mahendra Singh Dhoni, is a former Indian international cricketer and one of the most successful and iconic cricket captains in Indian history. He was born on July 7, 1981, in Ranchi, Jharkhand, India. Dhoni is widely known for his calm and composed demeanor on the cricket field and his leadership as the captain of the Indian cricket team.'),
('pv sindhu','Pusarla Venkata Sindhu, commonly known as P.V. Sindhu, is an Indian badminton player who is widely recognized for her achievements in the sport. She was born on July 5, 1995, in Hyderabad, India. P.V. Sindhu is known for her exceptional skills and accomplishments in womens singles badminton.'),
('sardar patel','Sardar Vallabhbhai Patel, often simply referred to as Sardar Patel, was a prominent Indian statesman and one of the founding fathers of the Republic of India. He was born on October 31, 1875, in Nadiad, Gujarat, India, and he passed away on December 15, 1950. Sardar Patel is particularly renowned for his pivotal role in the integration of princely states into the newly independent India.'),
('subhas chandra bose','Subhas Chandra Bose, often referred to as Netaji, was a prominent Indian nationalist leader who played a key role in the Indian independence movement against British colonial rule. He was born on January 23, 1897, in Cuttack, India, and his mysterious disappearance in 1945 remains a subject of intrigue and debate.'),
('amitabh bachchan','Amitabh Bachchan, often referred to as Big B, is one of the most iconic and influential actors in the Indian film industry, particularly in Bollywood. He was born on October 11, 1942, in Allahabad, India. Amitabh Bachchan is celebrated for his remarkable acting talent, charisma, and contributions to Indian cinema.')]
    cur.executemany("INSERT INTO data (name, about) VALUES (?, ?)", entries)
    con.commit()

con.close()
